version: '3'


services:
  entrypoint_proxy:
    image: "traefik:v2.10"
    container_name: "entrypoint_proxy"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      # TLS Config
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EP_LE_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # TLS Config
      - "./letsencrypt:/letsencrypt"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=(Host(`${EP_DOMAIN}`)&&PathPrefix(`/dashboard`,`/api`))"
      - "traefik.http.routers.traefik.entrypoints=${EP_PROTOCOL_LABEL}"
      - "traefik.http.routers.traefik.service=api@internal"
      # Basic Auth Config
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${DDCS_SERVICE_ENV_SECRET_EP_AUTH_USER_AND_HASH}"
      - "traefik.http.middlewares.traefik-auth.basicauth.removeheader=true"
      # TLS Config
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      # HTTP to HTTPS Redirect Config
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
